spring:
  datasource:
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    root: info
#    org:
#      apache:
#        coyote:
#          http11: debug
