spring:
  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  flyway:
    enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: info
#    org:
#      apache:
#        coyote:
#          http11: debug
